version: 2
jobs:
  build:
    docker:
      # Docker-image
      - image: circleci/python:3.7.0-stretch-node-browsers
    working_directory: ~/tube-friends
    steps:
      - checkout
      - run:
          # Show Branch
          name: Show Current Branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          # Install yarn Dependencies
          name: Install yarn Dependencies
          command: |
            sudo npm install
      - run:
          # Test codes
          name: Test code using jest
          command: npm run test
      - run:
          # Test codes
          name: Build app
          command: npm run build
      - run:
          # Install AWS CLI
          name: Install awscli
          command: |
            sudo pip install awsebcli --upgrade
      - run:
          # Create and Save AWS User Informations
          name: Create AWS credentials manually
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile eb-cli]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run:
          # Deploy
          name: Deploy to env
          command: |
            eb deploy MojiMojiProduction-env
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
